name: VariantBrush
version: '${version}'
main: me.clickism.variantbrush.VariantBrush
api-version: '1.21.5'
authors: [ Clickism ]
description: Use a brush to switch between pig, cow and chicken variants.